export const HeaderInfo = [
  {
    id: 1600,
    title: "MEN",
    listItem: [
      {
        subtitle: "Shoes",
        _id: "1700",
        listData: [
          "All Men's Shoes",
          "Sneakers",
          "Running",
          "Soccer",
          "Sandals & Slides",
          "Workout & Gym",
          "Hiking",
          "Basketball",
          "Shoes $100 & Under",
          "Golf",
          "Baseball",
          "Football",
        ],
      },
      {
        subtitle: "Clothing",
        _id: "1701",
        listData: [
          "All Men's Clothing",
          "T-Shirts & Tops",
          "Hoodies & Sweatshirts",
          "Shorts",
          "Pants",
          "Jackets",
          "Tracksuits",
          "Matching Sets",
          "Jerseys",
          "Tall",
        ],
      },
      {
        subtitle: "Accesories",
        _id: "1702",
        listData: [
          "All Men's Accesories",
          "Bags & Backpacks",
          "Balls",
          "Gloves",
          "Hats & Beanies",
          "Socks",
          "Underwear",
          "Water Bottles",
        ],
      },
      {
        subtitle: "New & Trending",
        _id: "1703",
        listData: [
          "All Men's New Arrivals",
          "All Men's Best Sellers",
          "Members Exclusives",
          "Gift Cards",
          "Ultraboost 1.0",
          `Trending Classics:
           Samba & Gazelle`,
          "Adicolor 70's",
          "Only at adidas",
          "Release Dates",
          "End Plastic Waste",
        ],
      },
      {
        subtitle: "Shop By Sport",
        _id: "1704",
        listData: [
          "Baseball",
          "Basketball",
          "Cycling",
          "Football",
          "Golf",
          "Hiking",
          "Hockey",
          "Outdoor",
          "Running",
          "Skateboarding",
          "Soccer",
          "Tennis",
          "Volleyball",
          "Workout & Gym",
          "Yoga",
        ],
      },
      {
        subtitle: "Shop by Collection",
        _id: "1705",
        listData: [
          "adicolor Clothing",
          "adilette Slides",
          "College Gear",
          "Five Ten",
          "Forum",
          "IVY PARK",
          "Originals",
          "Sportswear",
          "TERREX",
          "Ultraboost",
          "Y-3",
        ],
      },
      {
        subtitle: "Sale",
        _id: "1706",
        listData: ["All Sale", "Shoes", "Clothing", "Accessories"],
      },
    ],
  },
  {
    id: 1601,
    title: "WOMEN",
    listItem: [
      {
        subtitle: "Shoes",
        _id: "1707",
        listData: [
          "All Women's Shoes",
          "Sneakers",
          "Running",
          "Sandals & Slides",
          "Workout & Gym",
          "Shoes $100 & Under",
          "Hiking",
          "Soccer",
          "Tennis",
          "Platform Shoes",
          "Basketball",
          "Golf",
          "Softball",
          "Volleyball",
        ],
      },
      {
        subtitle: "Clothing",
        _id: "1708",
        listData: [
          "All Women's Clothing",
          "T-Shirts & Tops",
          "Hoodies & Sweatshirts",
          "Plus Sizes",
          "Tights & Leggins",
          "Shorts",
          "Sports Bras",
          "Pants",
          "Jackets",
          "Tracksuits",
          "Matching Sets",
          "Dresses & Skirts",
          "Maternity",
        ],
      },
      {
        subtitle: "Accessories",
        _id: "1709",
        listData: [
          "All Women's Accessories",
          "Bags & Backpacks",
          "Balls",
          "Gloves",
          "Hats & Headbands",
          "Headphones",
          "Socks",
          "Underwear",
          "Water Bottles",
        ],
      },
      {
        subtitle: "New & Trending",
        _id: "1710",
        listData: [
          "All Women's New Arrival",
          "All Women's Best Sellers",
          "Members Exclusives",
          "Gift Cards",
          "Ultraboost 1.0",
          "Trending Classics: Samba & Gazelle",
          "Adicolor 70's",
          "Only at adidas",
          "Release Dates",
          "End Plastic Waste",
        ],
      },
      {
        subtitle: "Shop by Sport",
        _id: "1711",
        listData: [
          "Basketball",
          "Cycling",
          "Golf",
          "Hiking",
          "Outdoor",
          "Running",
          "Soccer",
          "Softball",
          "Swim",
          "Tennis",
          "Volleyball",
          "Workout & Gym",
          "Yoga",
        ],
      },
      {
        subtitle: "Shop by Collection",
        _id: "1712",
        listData: [
          "adicolor Clothing",
          "adilette Slides",
          "College Gear",
          "Five Ten",
          "Forum",
          "IVY PARK",
          "Originals",
          "Sportswear",
          "TERREX",
          "Ultraboost",
          "Y-3",
        ],
      },
      {
        subtitle: "Sale",
        _id: "1713",
        listData: ["All Sale", "Shoes", "Clothing", "Accesories", "Final Sale"],
      },
    ],
  },
  {
    id: 1602,
    title: "KIDS",
    listItem: [
      {
        subtitle: "Boys",
        _id: "1714",
        listData: ["Shoes", "Clothing", "Accessories"],
      },
      {
        subtitle: "Girls",
        _id: "1715",
        listData: ["Shoes", "Clothing", "Accessories"],
      },
      {
        subtitle: "Babies & Toddlers",
        _id: "1716",
      },
      {
        subtitle: "New & Trending",
        _id: "1717",
        listData: [
          "New Arrivals",
          "Best Sellers",
          "Only at adidas",
          "Disney Collection",
          "LEGO Collection",
          "Summer Camp Must Haves",
          "Ultraboost 1.0",
          "Gift Cards",
          "Matching Sets",
        ],
      },
      {
        subtitle: "Accessories",
        _id: "1718",
        listData: [
          "Bags & Backpacks",
          "Hats & Beanies",
          "Socks",
          "Backpacks Under $50",
        ],
      },
      {
        subtitle: "Shop By Age",
        _id: "1719",
        listData: [
          "Youth & Teens (8-16 years)",
          "Children (4-8 years)",
          "Babies & Toddlers(0-4 years)",
        ],
      },
      {
        subtitle: "Shop by Sport",
        _id: "1720",
        listData: [
          "Baseball",
          "Basketball",
          "Football",
          "Golf",
          "Outdoor",
          "Running",
          "Soccer",
          "Softball",
          "Training",
          "Volleyball",
          "Yoga",
        ],
      },
      {
        subtitle: "Sale",
        _id: "1721",
        listData: [
          "All Kids Sale",
          "Boys Sale",
          "Girls Sale",
          "Shoes",
          "Clothing",
          "Accessories",
        ],
      },
      {
        subtitle: "All Kids",
        _id: "1722",
      },
    ],
  },
  {
    id: 1603,
    title: "3 STRIPE LIFE",
    listItem: [
      {
        subtitle: "What's New",
        _id: "1723",
        listData: [
          "Impossible is Nothing",
          "New Arrivals",
          "Best Sellers",
          "Release Dates",
          "Stories",
        ],
      },
      {
        subtitle: "Collaborations",
        _id: "1724",
        listData: [
          "IVY PARK",
          "Pharrell",
          "Prada",
          "Craig Green",
          "Bad Bunny",
          "Human Made",
          "Y-3",
          "Stella McCartney",
          "Consortium",
          "Collaborations",
        ],
      },
      {
        subtitle: "Our World",
        _id: "1725",
        listData: [
          "Purpose",
          "Sustainability",
          "FutureCraft",
          "adidas Legacy",
          "adiClub",
          "Made To Be Remade",
        ],
      },
      {
        subtitle: "Sports",
        _id: "1726",
        listData: [
          "Baseball",
          "Basketball",
          "Football",
          "Golf",
          "Hockey",
          "Outdoor",
          "Running",
          "Soccer",
          "Skateboarding",
          "Tennis",
          "Workout",
          "Volleyball",
          "Weightlifting",
          "Yoga",
        ],
      },
      {
        subtitle: "Originals",
        _id: "1727",
        listData: [
          "Superstar",
          "adilette",
          "ZX",
          "adicolor Clothing",
          "NMD",
          "Stan Smith",
          "Samba",
          "Gazelle",
          "Oz",
          "Forum",
          "Original Shoes",
          "Originals Clothing",
        ],
      },
      {
        subtitle: "Collections",
        _id: "1728",
        listData: [
          "adiZero",
          "Copa",
          "4D",
          "Five Ten",
          "Predator",
          "Supernova",
          "TERREX",
          "Tiro",
          "Ultraboost",
          "X",
          "Slides",
        ],
      },
      {
        subtitle: "Shop All",
        _id: "1729",
      },
    ],
  },
  {
    id: 1604,
    title: "SALE",
    listItem: [
      {
        subtitle: "All Sale",
        _id: "1730",
      },
      {
        subtitle: "Mens Sale",
        _id: "1731",
      },
      {
        subtitle: "Womens Sale",
        _id: "1732",
      },
      {
        subtitle: "Kids Sale",
        _id: "1733",
      },
      {
        subtitle: "Final Sale",
        _id: "1734",
      },
      {
        subtitle: "Up to 40% off Sale",
        _id: "1735",
      },
    ],
  },
];

export const HeaderInfoWomen = [];

export const HeaderInfoKids = [];

export const HeaderInfo3Stripe = [
  {
    id: 1603,
    title: "3 STRIPE LIFE",
    listItem: [
      {
        subtitle: "What's New",
        _id: "1723",
        listData: [
          "Impossible is Nothing",
          "New Arrivals",
          "Best Sellers",
          "Release Dates",
          "Stories",
        ],
      },
      {
        subtitle: "Collaborations",
        _id: "1724",
        listData: [
          "IVY PARK",
          "Pharrell",
          "Prada",
          "Craig Green",
          "Bad Bunny",
          "Human Made",
          "Y-3",
          "Stella McCartney",
          "Consortium",
          "Collaborations",
        ],
      },
      {
        subtitle: "Our World",
        _id: "1725",
        listData: [
          "Purpose",
          "Sustainability",
          "FutureCraft",
          "adidas Legacy",
          "adiClub",
          "Made To Be Remade",
        ],
      },
      {
        subtitle: "Sports",
        _id: "1726",
        listData: [
          "Baseball",
          "Basketball",
          "Football",
          "Golf",
          "Hockey",
          "Outdoor",
          "Running",
          "Soccer",
          "Skateboarding",
          "Tennis",
          "Workout",
          "Volleyball",
          "Weightlifting",
          "Yoga",
        ],
      },
      {
        subtitle: "Originals",
        _id: "1727",
        listData: [
          "Superstar",
          "adilette",
          "ZX",
          "adicolor Clothing",
          "NMD",
          "Stan Smith",
          "Samba",
          "Gazelle",
          "Oz",
          "Forum",
          "Original Shoes",
          "Originals Clothing",
        ],
      },
      {
        subtitle: "Collections",
        _id: "1728",
        listData: [
          "adiZero",
          "Copa",
          "4D",
          "Five Ten",
          "Predator",
          "Supernova",
          "TERREX",
          "Tiro",
          "Ultraboost",
          "X",
          "Slides",
        ],
      },
      {
        subtitle: "Shop All",
        _id: "1729",
      },
    ],
  },
];

export const HeaderInfoSale = [
  {
    id: 1604,
    title: "SALE",
    listItem: [
      {
        subtitle: "All Sale",
        _id: "1730",
      },
      {
        subtitle: "Mens Sale",
        _id: "1731",
      },
      {
        subtitle: "Womens Sale",
        _id: "1732",
      },
      {
        subtitle: "Kids Sale",
        _id: "1733",
      },
      {
        subtitle: "Final Sale",
        _id: "1734",
      },
      {
        subtitle: "Up to 40% off Sale",
        _id: "1735",
      },
    ],
  },
];
